### PR TITLE
Puma 6 support

### PR DESCRIPTION
**Pull request by iscra**
Changes  for compatibility with Puma 6, requires Puma 6 (incompatible Puma::Server.new changes)

### CODE REVIEW

**Comment by tomasc** [comment]
thanks @iscra , would be great to have this merged!

**Comment by tomasc** [comment]
@platbr would be wonderful to have this merged, thank you!

**Comment by platbr** [comment]
Sorry guys, I almost missed it. I'm going to check it.

**Comment by tomasc** [comment]
@platbr amazing, thanks!

**Comment by platbr** [comment]
Puma 6 support was added and it still Puma 5 compatible. Tag v3.8.0

**Pull request merged**
